version: '3.8'

services:
  ray_api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - RAY_MEMORY_LIMIT=2GB  # Adjust memory as per your requirement
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2GB
    restart: always
